#!/bin/sh

start() {
	echo -n "Mounting /dev/sda1 to /media :"
	mount /dev/sda1 /media && echo "OK" || echo "KO"
}

stop() {
	echo -n "Unmounting /dev/sda1"
	umount /dev/sda1 && echo "OK" || echo "KO"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
