#!/bin/sh -e
#
# Description:       Load the modules listed in /etc/modules.
#

# Silently exit if the kernel does not support modules.
[ -f /proc/modules ] || exit 0
[ -x /sbin/modprobe  ] || exit 0


PATH='/sbin:/bin'

case "$1" in
  start)
  ;;

  stop|restart|reload|force-reload)
  echo "Action '$1' is meaningless for this init script"
  exit 0
  ;;

  *)
  echo "Usage: $0 start"
  exit 1
esac

load_module() {
  local module args
  module="$1"
  args="$2"

  if [ "$VERBOSE" != no ]; then
    echo "Loading kernel module $module"
    modprobe $module $args || true
  else
    modprobe $module $args > /dev/null 2>&1 || true
  fi
}

modules_files() {
    echo /etc/modules
}

if [ "$VERBOSE" = no ]; then
  echo 'Loading kernel modules'
fi

files=$(modules_files)
if [ "$files" ] ; then
  grep -h '^[^#]' $files |
  while read module args; do
    [ "$module" ] || continue
    load_module "$module" "$args"
  done
fi

if [ "$VERBOSE" = no ]; then
  echo 0
fi

