#!/bin/sh
#
# Starting hostapd...
#

case "$1" in
  start)
 	echo "Starting hostapd..."
	hostapd -B /etc/hostapd/hostapd.conf
	;;
  restart|reload)
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|restart}"
	exit 1
esac

exit $?

